[package]
name = "octo-wm"
version = "0.1.0"
authors = ["Rivee <victor.hognon@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.73"
x11 = { version = "2.18.2", features = ["xlib"] }
